### ISSUE TITLE
Win 7 on screen keyboard is accessible on new Installer

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#161]
**How to recreate**
1. Run the latest installer on Win 7 Pro embedded and start the Player
2. Switch to CMD with the Player running. In CMD execute taskkill /f /im explorer.exe
3. Switch to Player.  User is able to swipe to keyboard (or the 'Tablet PC Input Panel') left to center. On centre-left of the edge of the screen, tap once to reveal the edge then swipe left.

This is on Win 7 Pro embedded out of the box with no changes to system settings/optmizations. 

**How it should run**
When I run an interactive presentation on Win 7 Pro embedded, I should not have the on screen keyboard accessible.

**Comment by fjvallarino** [comment]
@hcs0 This is not currently an issue, since it was part of the testing process to check if this solution worked fine in all versions of Windows 10 and not something that happened while running the installer. We have implemented this feature (it's not part of the package CS currently testing) taking into account this problem, so we are not killing explorer.exe on Windows 7. I'll close this issue and, in case this problem arises again, we can create a new one.
