### ISSUE TITLE
Running the Installer with a non working Proxy does not show the Proxy config page

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#382]
<b>How it works now:</b>
1. Set up a non working proxy in Internet Settings, and confirm you cannot get out to the internet.
2. Run the installer, and notice that it does not ask for Proxy settings. When Player starts, it sits on a loading animation.

<b>How it should work:</b>
Upon **attended** installation, the proxy screen is displayed and proxy settings can be validated and display id can be registered / verified

**Comment by hcs0** [comment]
I can recreate on Linux x64

**Comment by tejohnso** [comment]
I've submitted an update for Blake's review.  It's still not going to show the proxy settings at startup because the player works fine with the default of no proxy.  It doesn't use the windows proxy config.  When player starts, it should no longer sit on the loading animation.  It should work properly.

**Comment by btfrise** [comment]
@tejohnso Fix provided in new installer works.

**Comment by tejohnso** [comment]
@robb-price I think we can close this now?  @btfrise

**Comment by robb-price** [comment]
@tejohnso Yup, Verified and closed.
