### ISSUE TITLE
Player Professional does not work offline in certain instances

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#656]
<b>How it works now:</b>
If the internet is disconnected from the Media Player, Rise Vision Player Professional recognizes the internet is disconnected.

But If the internet is disconnected from the uplink port on the network switch, Windows still detects a valid network link. In this case the computer cannot access the Internet, but Rise Vision Player Professional does NOT play the offline content. Instead it displays a 100% white frame and keeps trying to restart itself. The same thing happens when a firewall is turned on to block the media player from the Internet.

<b>How it should work:</b>
Rise Vision Player Professional continues to show cached content in all the above instances.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Issue 656 - Rise Player Pro does not work in all disconnected instances](https://trello.com/c/3NuvqmQB/6776-2-issue-656-rise-player-pro-does-not-work-in-all-disconnected-instances)

**Comment by alanclayton** [comment]
This is working as designed. We have work planned to improve this scenario so content is shown on slow networks.

**Comment by alanclayton** [comment]
To clarify on the previous comment re: work planned to improve the scenario. The problem w/ pursing this improvement now is due to the use of Viewer and the complexity associated with it. We are going to work to move away from Viewer which  will allow us to more easily implement the logic to handle showing content when offline in addition to poor network situation.
