### ISSUE TITLE
During uninstall on older devices, rvplayer folder is not deleted due to folders not being empty.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#786]
**Describe the bug**
When trying to remove Rise Player to update or for any other reason, the rvplayer reports errors in removing specific folders, and does not delete the rvplayer folder.

**Reach**
So far this only appears to occur on older Displays that have auto updated several times.

**Impact**
Not high impact, simply delete the rvplayer folder manually before you reinstall.

**Screenshots**
![2019-02-12_09-30-33](https://user-images.githubusercontent.com/6862256/52729527-5aaeb400-2f87-11e9-993a-cd05cc74df28.png)

**Desktop (please complete the following information):**
 - OS: So far this occurs on both Linux and Windows.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Issue 786: During uninstall on older devices, rvplayer folder is not deleted due to folders not being empty.](https://trello.com/c/ax6qt1dE/9432-3-issue-786-during-uninstall-on-older-devices-rvplayer-folder-is-not-deleted-due-to-folders-not-being-empty)

**Comment by alanclayton** [comment]
@robb-price can you clarify what problem occurs as a result of this?

**Comment by robb-price** [comment]
@alanclayton The 2 users who reported this said that when they did not remove the rvplayer folder manually, Player did not work correctly when they reinstalled.

**Comment by alanclayton** [comment]
@robb-price Sorry, I still don't understand the situation. Please answer the following:

Re: your comment on Reach, "only appears to occur on older displays that have updated many times"
1.  What is your definition of "older display". 
2. What do you mean by "...have updated many times". Does the problem not occur after the first update? 
3. Re: Player not working, what specifically didn't work? Did Player not start? Did Player start, but content not load, etc? 
4. What are the steps to replicate? 

@tejohnso FYI.

**Comment by robb-price** [comment]
@alanclayton 
1. Older Display means a Display that has had Player installed on it, and updated several times automatically.

2. Updated many times means the Player has updated itself automatically several times after the initial installation.

3. According to the user, the Player stays at a loading animation, similar to Issue 785.

I cannot confirm this, but I wonder if the user's copied the RiseDisplayNetworkII.ini file from the rvplayer folder, reinstalled, and instead of typing in the Player ID, copied that file back to the rvplayer folder. This way, the same Core and Viewer URL's from Issue 785 would still be there, and this is effectively issue 785. 

4. This can only be replicated on a machine that had a previous version of Rise Vision Player on it, and was updated automatically via Player.

If my suspicion is correct, I recommend we close this bug, correct issue 785, and see if any reports of this return.

**Comment by alanclayton** [comment]
@tejohnso can you review and confirm how you want to proceed with this?

**Comment by tejohnso** [comment]
@alanclayton @robb-price I just tried the `rd` command directly in the terminal on a dev box that has had plenty of upgrades. The issue was reproduced, showing a "not empty" message. After running the exact same command again, I saw another "not empty" message but I noticed the directory was emptier than the previous run. So I ran it a third time, and it finally finished with no error and the directory was completely gone. That's not the way the `rd` command is supposed to work.

It looks like it's a [common problem](https://stackoverflow.com/a/22949687) on windows. That report is similar to what I experienced except for me it failed twice in a row and worked only on the third time.

I think the simplest option is to add multiple `rd` commands to the uninstall script. We can add it to this week's rollout.
