### ISSUE TITLE
Rise Player on Win 10 sometimes doesn't automatically start

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#816]
**Describe the bug**
Rise Player doesn't start automatically.  After reinstalling or manually placing the lnk file into the startup folder, it will start automatically for a few days, but at some point the file disappears from startup.

When the issue is happening, this error is logged when Rise Player is started manually: [enoent.txt](https://github.com/Rise-Vision/rise-launcher-electron/files/3623347/enoent.txt)

We verified the install path is correct on the affected machine, but the Rise Vision Player.lnk file it's trying to rename doesn't exist on either a working machine or the affected machine.

**Reach**
This is currently reaching several displays for a single customer.  Not all players are affected at the same time, but they've had at least 20 of them affected at one time.

**Impact**
There is a workaround, which is to reinstall player from scratch or manually place the lnk file in the startup directory.  It will work for a seemingly unpredictable amount of time, and suddenly fail again.

**To Reproduce**
I haven't been able to reproduce this behavior on my player.  We can coordinate with the customer to work with an affected player as needed.  I'll provide additional details in the card.

**Expected behavior**
Rise Player starts automatically when the Media Player is started.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 Education

**Additional context**
- These affected players are on a domain.  It may be related to the issue, but we're not sure.

**Comment by olegrise** [comment]
Couple of things here:
1) It seems that the root of the problem is that Player autostart shortcut is being created under [`process.env.APPDATA](https://github.com/Rise-Vision/rise-common-electron/blob/0e1c39d350eefb047b73176d3cb519fc0a34c245/platform.js#L76) folder. The problem with `process.env.APPDATA` is that it points to "C:\\Users\\username\\AppData\\**Roaming**\\". The roaming folder can move with user profile from PC to PC ([more details](https://support.pointlogic.com/faq/troubleshooting/accessing-the-appdata-folder)). The alternative is to use `process.env.ALLUSERSPROFILE` which will install shortcut for all users on that machine.
2) There is a chance that the shortcut is being removed by Windows Maintenance ([see here](https://www.ghacks.net/2010/03/30/fix-windows-7-desktop-shortcuts-disappearing/)). It should be an easy task to turn off Windows Maintenance and see if that help.

@tejohnso any thoughts on the above?

**Comment by PatrickA-RiseVision** [comment]
@olegrise is this what we're relaying to the customer, or are we waiting on confirmation from Tyler?

**Comment by tejohnso** [comment]
My suggestion would be %LOCALAPPDATA% which is still a **per-user** configuration file location but without the sync features. It's local to one machine. I'm not sure autostart files will work there though so we'd have to test it. And if we were to make this change we'd have to be careful about avoiding duplicate startup files.

Ideally the user can turn off maintenance and keep the computer out of a domain then we'd be able to  confirm that works as well.

**Comment by PatrickA-RiseVision** [comment]
@tejohnso @olegrise doesn't player already install in %LOCALAPPDATA%?   Or does that just happen to be the location of process.env.APPDATA if the device is in a workgroup?

We've already asked them to remove the computer from the domain, and they've refused.
